version: "3.9"

services:
  nextjs-app:
    container_name: qasr-alsultan-store
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "server.js"]

    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 3000
      

    ports:
      - "80:3000"


    networks:
      - qasr-alsultan-store

    restart: unless-stopped


 

networks:
  qasr-alsultan-store:
    driver: bridge
